-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Июл 18 2025 г., 17:13
-- Версия сервера: 8.0.30
-- Версия PHP: 8.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `autosygnals`
--

-- --------------------------------------------------------

--
-- Структура таблицы `Products`
--

CREATE TABLE `Products` (
  `id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `category` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `model` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_general_ci,
  `price` decimal(10,2) NOT NULL,
  `currency` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `quantity` int DEFAULT '1',
  `link` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_popular` tinyint(1) DEFAULT '0',
  `is_special` tinyint(1) DEFAULT '0',
  `gallery` json DEFAULT NULL,
  `functions` json DEFAULT NULL,
  `options` json DEFAULT NULL,
  `options_filters` json DEFAULT NULL,
  `autosygnals` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Дамп данных таблицы `Products`
--

INSERT INTO `Products` (`id`, `category`, `model`, `title`, `description`, `price`, `currency`, `quantity`, `link`, `is_popular`, `is_special`, `gallery`, `functions`, `options`, `options_filters`, `autosygnals`, `created_at`, `updated_at`) VALUES
('product_keychain_a60', 'keychain', 'a60', 'Starline A60 Eco', 'Умный охранно-телематический комплекс StarLine А60 включает лучшие решения в области автобезопасности и гарантирует надежную защиту от угона благодаря устойчивому к электронному взлому диалоговому коду управления и широким возможностям для авторских блокировок двигателя. А гибкие настройки сервисных функций подарят вашему автомобилю уровень комфорта премиум-класса', '43700.00', '₸', 1, '/product?category=keychain&id=product_keychain_a60', 0, 0, '[\"http://localhost:3000/client/images/products/starline_a60/package_Starline-A60-Eco.avif\", \"http://localhost:3000/client/images/products/starline_a60/Starline-A60-Eco-3.avif\", \"http://localhost:3000/client/images/products/starline_a60/Starline-A60-Eco-2.avif\", \"http://localhost:3000/client/images/products/starline_a60/Starline-A60-Eco-1.avif\"]', '[]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"without-auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 14:13:16'),
('product_keychain_a63', 'keychain', 'a63', 'Starline A63 V2', 'Надежный автомобильный охранно-телематический комплекс с несканируемым диалоговым кодом управления, опциональными 2CAN+2LIN и GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '58300.00', '₸', 1, '/product?category=keychain&id=product_keychain_a63', 0, 0, '[\"/client/images/products/starline_a63/package-starline-a63.avif\", \"/client/images/products/starline_a63/keychain-Starline-A63-ECO-V2.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\", \"/client/images/products/starline_a93/keychain_a93-v2-3.avif\"]', '[]', '[]', '[]', '[\"without-auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a63-eco-v2', 'keychain', 'a63-eco-v2', 'Starline A63 ECO V2', 'Надежный автомобильный охранно-телематический комплекс с несканируемым диалоговым кодом управления, опциональными 2CAN+2LIN и GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м. Комплектуется только с 1 пультом ДУ.', '50300.00', '₸', 1, '/product?category=keychain&id=product_keychain_a63-eco-v2', 0, 0, '[\"/client/images/products/starline_a63/package-starline-a63-eco.avif\", \"/client/images/products/starline_a63/keychain-Starline-A63-ECO-V2.avif\"]', '[\"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\"]', '[]', '[\"block-engine-can\"]', '[\"without-auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a90', 'keychain', 'a90', 'Starline A90 Eco', 'Умный охранно-телематический комплекс StarLine B97 с интегрированными GSM или LTE и GPS+ГЛОНАСС интерфейсами включает лучшие решения в области автобезопасности и гарантирует надежную защиту от угона благодаря устойчивому к электронному взлому диалоговому коду управления, широким возможностям для авторских блокировок двигателя, обеспечивающим защиту от ретрансляции, уникальному трансиверу для работы в условиях экстремальных городских радиопомех. Вашему автомобилю подарят функции комфорта премиум-класса: Умная цифровая интеграция 3CAN+4LIN 60 программ гибкой логики Bluetooth Smart-интерфейс', '60200.00', '₸', 1, '/product?category=keychain&id=product_keychain_a90', 0, 0, '[\"/client/images/products/starline_a90/package-Starline-A90-Eco.avif\", \"/client/images/products/starline_a60/Starline-A60-Eco-3.avif\", \"/client/images/products/starline_a60/Starline-A60-Eco-2.avif\", \"/client/images/products/starline_a60/Starline-A60-Eco-1.avif\"]', '[\"Автозапуск\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\"]', '[\"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a93-2can-2lin', 'keychain', 'a93-2can-2lin', 'Starline A93 2CAN 2LIN ECO V2', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, интегрированным 2CAN+2LIN интерфейсом, опциональным GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, SUPER SLAVE авторизацией, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '99800.00', '₸', 1, '/product?category=keychain&id=product_keychain_a93-2can-2lin', 0, 0, '[\"/client/images/products/starline_a93/package-starline-a93-2can-2lin-eco.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\"]', '[\"Автозапуск\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"block-engine-can\", \"control-before-start\"]', '[\"auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a93-2can-2lin-gsm', 'keychain', 'a93-2can-2lin-gsm', 'Starline A93 V2 2CAN+2LIN GSM ECO', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, интегрированными 2CAN+2LIN и GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, SUPER SLAVE авторизацией, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '159000.00', '₸', 1, '/product?category=keychain&id=product_keychain_a93-2can-2lin-gsm', 0, 0, '[\"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\", \"/client/images/products/starline_a93/starline-А93-v2-ECO.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"block-engine-can\", \"control-before-start\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a93-eco', 'keychain', 'a93-eco', 'Starline A93 ECO V2', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, опциональными 2CAN+2LIN и GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '64900.00', '₸', 1, '/product?category=keychain&id=product_keychain_a93-eco', 1, 1, '[\"/client/images/products/starline_a93/starline-A93-ECO-V2-main.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\", \"/client/images/products/starline_a93/package-Starline-A93-2CAN-2LIN-ECO-V2.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-before-start\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a93-v2', 'keychain', 'a93-v2', 'StarLine A93 V2', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, опциональными 2CAN+LIN и GSM интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '74300.00', '₸', 1, '/product?category=keychain&id=product_keychain_a93-v2', 0, 0, '[\"/client/images/products/starline_a93/starline-A93-ECO-V2-main.avif\", \"/client/images/products/starline_a93/package-Starline-A93-2CAN-2LIN-ECO-V2.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-before-start\"]', '[\"auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_a93-v2-gsm', 'keychain', 'a93-v2-gsm', 'Starline A93 V2 GSM', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, GSM интерфейсом, опциональными 2CAN+2LIN интерфейсами, опциональным GPS-ГЛОНАСС мониторингом, ударопрочным брелком управления, 128-канальным помехозащищенным трансивером с дальностью оповещения до 2000 м', '122700.00', '₸', 1, '/product?category=keychain&id=product_keychain_a93-v2-gsm', 0, 0, '[\"/client/images/products/starline_a93/starline-A93-ECO-V2-main.avif\", \"/client/images/products/starline_a93/package-Starline-A93-2CAN-2LIN-ECO-V2.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"control-before-start\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_b97', 'keychain', 'b97', 'Автосигнализация StarLine B97 2SIM BT LTE-GPS', 'Умный охранно-телематический комплекс StarLine B97 с интегрированными GSM или LTE и GPS+ГЛОНАСС интерфейсами включает лучшие решения в области автобезопасности и гарантирует надежную защиту от угона благодаря устойчивому к электронному взлому диалоговому коду управления, широким возможностям для авторских блокировок двигателя, обеспечивающим защиту от ретрансляции, уникальному трансиверу для работы в условиях экстремальных городских радиопомех. Вашему автомобилю подарят функции комфорта премиум-класса: Умная цифровая интеграция 3CAN+4LIN 60 программ гибкой логики Bluetooth Smart-интерфейс', '298700.00', '₸', 1, '/product?category=keychain&id=product_keychain_b97', 0, 0, '[\"/client/images/products/starline_b97/StarLine-B97-2SIM-BT-LTE-GPS.avif\", \"/client/images/products/starline_b97/StarLine-B97-2SIM-BT-LTE-GPS-1.avif\", \"/client/images/products/starline_b97/StarLine-B97-2SIM-BT-LTE-GPS-2.avif\", \"/client/images/products/starline_b97/StarLine-B97-2SIM-BT-LTE-GPS-3.avif\", \"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM.avif\", \"/client/images/products/starline_b97/package-StarLine-B97-2SIM-BT-LTE-GPS.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_e96-2can-4lin-gsm', 'keychain', 'e96-2can-4lin-gsm', 'StarLine E96 V2 BT 2CAN+4LIN 2SIM GSM+GPS', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском с вашего смартфона, несканируемым диалоговым кодом управления, возможностью авторизации по защищенной технологии через смартфон и метку, интегрированным 2CAN+4LIN. Благодаря GSM+GPS интерфейсу обеспечивается возможность управления комплексом из любой точки мира.', '167200.00', '₸', 1, '/product?category=keychain&id=product_keychain_e96-2can-4lin-gsm', 1, 0, '[\"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN.avif\", \"/client/images/products/starline_e96/package-StarLine-E96-v2-BT-2CAN-4LIN-2SIM-GSM-GPS.avif\", \"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN-1.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\"]', '[\"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_e96-eco', 'keychain', 'e96-eco', 'StarLine E96 V2 BT ECO 2CAN+4LIN', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском, несканируемым диалоговым кодом управления, возможностью авторизации по защищенному протоколу через персональную метку или смартфон на iOS и Android с мобильным приложением StarLine, интегрированным 2CAN+4LIN интерфейсом, ударопрочным брелком управления, помехозащищенным трансивером с малошумящим усилителем', '99800.00', '₸', 1, '/product?category=keychain&id=product_keychain_e96-eco', 1, 1, '[\"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN.avif\", \"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN-1.avif\", \"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN-2.avif\", \"/client/images/products/starline_e96/ppackage-StarLine-E96-V2-BT-ECO-2CAN-4LIN.avif\"]', '[]', '[]', '[]', '[\"auto\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_e96-gsm', 'keychain', 'e96-gsm', 'Starline E96 V2 BT GSM', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском с вашего смартфона, несканируемым диалоговым кодом управления, возможностью авторизации по защищенной технологии через смартфон и метку, интегрированным 2CAN+4LIN. Благодаря GSM интерфейсу обеспечивается возможность управления комплексом из любой точки мира.', '147100.00', '₸', 1, '/product?category=keychain&id=product_keychain_e96-gsm', 0, 1, '[\"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN.avif\", \"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN-1.avif\", \"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN-2.avif\", \"/client/images/products/starline_e96/package-Starline-E96-V2-BT-GSM.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_s96-2can-2lin-gsm', 'keychain', 's96-2can-2lin-gsm', 'StarLine S96 V2 BT 2CAN2LIN GSM', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском с вашего смартфона, несканируемым диалоговым кодом управления, возможностью авторизации по технологии Bluetooth Smart, интегрированными 2CAN+2LIN и GSM интерфейсами.', '113600.00', '₸', 1, '/product?category=keychain&id=product_keychain_s96-2can-2lin-gsm', 1, 1, '[\"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM.avif\", \"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM-2.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_s96-2can-4lin', 'keychain', 's96-2can-4lin', 'Starline S96 V2 BT 2CAN 4LIN 2SIM GPS', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском с вашего смартфона, несканируемым диалоговым кодом управления, интегрированными 2CAN+2LIN и GSM интерфейсами, авторизацией по технологии Bluetooth Smar', '140000.00', '₸', 1, '/product?category=keychain&id=product_keychain_s96-2can-4lin', 0, 0, '[\"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM.avif\", \"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM-2.avif\", \"/client/images/products/starline_s96/package-StarLine-S96-V2-BT-2CAN-2LIN-GSM.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_keychain_s96-lte', 'keychain', 's96-lte', 'Starline S96 V2 BT LTE', 'Надежный автомобильный охранно-телематический комплекс с интеллектуальным автозапуском с вашего смартфона, несканируемым диалоговым кодом управления, возможностью авторизации по защищенной технологии через смартфон и метку, интегрированным 2CAN+4LIN. Благодаря GSM интерфейсу обеспечивается возможность управления комплексом из любой точки мира.м', '128200.00', '₸', 1, '/product?category=keychain&id=product_keychain_s96-lte', 0, 0, '[\"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM-2.avif\", \"/client/images/products/starline_s96/StarLine-S96-V2-BT-2CAN-2LIN-GSM.avif\", \"/client/images/products/starline_s96/package-starline-S96-v2-lte.avif\"]', '[\"Автозапуск\", \"УПРАВЛЕНИЕ С ТЕЛЕФОНА\", \"БЕСПЛАТНЫЙ МОНИТОРИНГ\", \"УМНАЯ АВТОРИЗАЦИЯ ПО BLUETOOTH SMART\", \"БЛОКИРОВКА ДВИГАТЕЛЯ ПО CAN\", \"УПРАВЛЕНИЕ ПРЕДПУСКОВЫМ ПОДОГРЕВОМ\", \"УМНАЯ АВТОДИАГНОСТИКА\", \"ДАННЫЕ О ПРОБЕГЕ И УРОВНЕ ТОПЛИВА\"]', '[\"Для легкового авто\", \"Для внедорожника\"]', '[\"vnedorojnik\", \"legkoe-avto\", \"autosetup\", \"control-phone\", \"free-monitoring\", \"bluetooth-smart\", \"block-engine-can\", \"control-before-start\", \"smart-diagnostic\", \"data-level-bensin\"]', '[\"auto\", \"gsm\", \"starline\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_camera-c1100', 'park-systems', 'camera-c1100', 'Камера заднего вида Alpine HCE C1100', 'Камера заднего вида Alpine HCE C1100 - превосходное качество, широкий угол обзора.', '65000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_camera-c1100', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-alpine-hce-c1-100/camera-rear-view-alpine-hce-c1-100-1.avif\", \"/client/images/products/park-systems/camera-rear-view-alpine-hce-c1-100/camera-rear-view-alpine-hce-c1-100-2.avif\", \"/client/images/products/park-systems/camera-rear-view-alpine-hce-c1-100/camera-rear-view-alpine-hce-c1-100-3.avif\", \"/client/images/products/park-systems/camera-rear-view-alpine-hce-c1-100/camera-rear-view-alpine-hce-c1-100-4.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_camera-ccd', 'park-systems', 'camera-ccd', 'Камера заднего вида CCD', 'Камера заднего вида с четким изображением и CCD матрицей', '12000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_camera-ccd', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-ccd/camera-rear-view-ccd.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_camera-cmos130', 'park-systems', 'camera-cmos130', 'Камера заднего вида Kenwood CMOS-130', 'Kenwood CMOS-130 - обычная камера заднего вида, без разметки.', '35000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_camera-cmos130', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-kenwood-cmos-130/camera-rear-view-kenwood-cmos-130.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_camera-prado150', 'park-systems', 'camera-prado150', 'Камера заднего вида на Toyota Prado 150', 'Инфракрасная камера заднего вида для Toyota Prado 150, оборудованная 4 красными светодиодами для ночного виденья, прекрасно поможет Вам запарковаться в любое время суток! Камера выполнена в черном пластиковом водонепроницаемом корпусе. Данная модель может подойти и на другие автомобили, имеющие небольшое квадратное отверстие на крышке багажника для крепления камеры.', '15000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_camera-prado150', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-toyota-prado-150/camera-rear-view-toyota-prado-150-1.avif\", \"/client/images/products/park-systems/camera-rear-view-toyota-prado-150/camera-rear-view-toyota-prado-150-2.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_cj-178', 'park-systems', 'cj-178', 'Камера заднего вида CJ-178', 'Камера заднего вида с инфракрасной подсветкой и углом обзора 140 градусов. Модель CJ-178 снабжена четырьмя LED диодами инфракрасной подсветки и имеется возможность регулировки камеры по вертикали, т.о. это делает камеру универсальной для установки на широкий круг автомобилей.', '10000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_cj-178', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-cj-178/camera-rear-view-cj-178-1.avif\", \"/client/images/products/park-systems/camera-rear-view-cj-178/rear-view-camera-cj-178-2.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_cj-188', 'park-systems', 'cj-188', 'Камера заднего вида CJ-188', 'Видеокамера заднего обзора универсальная с инфракрасной подсветкой CJ-188 хорошо впишется в пространство рядом с фонарем подсветки номера. Особенность модели в том, что она самая маленькая среди своих собратьев имеющих инфракрасную подсветку, камера незаметна при монтаже. Благодаря инфракрасной подсветке парковка ночью будет безопасной и приятной, так как подсветка помогает камере видеть ночью до 5 метров в черно-белом изображении, а днем показывает цветным.', '10000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_cj-188', 0, 0, '[\"/client/images/products/park-systems/camera-rear-view-cj-188/full_camera-rear-view-CJ-188-1.avif\", \"/client/images/products/park-systems/camera-rear-view-cj-188/full_camera-rear-view-CJ-188-2.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_park-systems_number-plate-with-camera', 'park-systems', 'number-plate-with-camera', 'Подномерник с камерой заднего вида', 'Камера в номерной рамке завоевала большую популярность среди автомобилистов благодаря своей универсальности. Основное ее преимущество - это особенность установки. Ведь ее можно установить практически на любой автомобиль вместо рамки номерного знака. Камера в номерной рамке имеет центральное расположение камеры, что дает возможность максимально по центру получать изображение с камеры.', '15000.00', '₸', 1, '/product?category=park-systems&id=product_park-systems_number-plate-with-camera', 0, 0, '[\"/client/images/products/park-systems/number-plate-with-camera/number-plate-with-rear-view-camera-1.avif\", \"/client/images/products/park-systems/number-plate-with-camera/number-plate-with-rear-view-camera-2.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_20w', 'remote-controls', '20w', 'Сирена 20W', 'Сирена для автосигнализаций', '3500.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_20w', 0, 0, '[\"/client/images/products/remote-controls/alarm-siren-20w-1.avif\", \"/client/images/products/remote-controls/alarm-siren-20w-2.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_a91-61', 'remote-controls', 'a91-61', 'Пульт Starline A91/61', 'Пульт на автосигнализацию Starline A91/A61 с жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_a91-61', 0, 0, '[\"/client/images/products/starline_a91/remote-controls-starline-a91.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_a93-a63', 'remote-controls', 'a93-a63', 'Пульт Starline A93/A63', 'Пульт на автосигнализацию Starline A93/A63 с жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_a93-a63', 0, 0, '[\"/client/images/products/starline_a93/starline-A93-ECO-V2-main.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-1.avif\", \"/client/images/products/starline_a93/keychain-Starline-A93-ECO-V2-2.avif\", \"/client/images/products/starline_a93/package-starline-a93-2can-2lin-eco.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_a96-a66', 'remote-controls', 'a96-a66', 'Пульт Starline A96/A66', 'Пульт на автосигнализацию Starline A96/A66 с жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_a96-a66', 0, 0, '[\"/client/images/products/starline_a96/remote-controls-Starline-A96-A66.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_b96-b66', 'remote-controls', 'b96-b66', 'Пульт Starline B96/B66', 'Пульт на автосигнализацию Starline B96/B66 с жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_b96-b66', 0, 0, '[\"/client/images/products/starline_b96/remote-controls-starline-b96-b66.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_d96', 'remote-controls', 'd96', 'Пульт Starline D96', 'Пульт на автосигнализацию Starline D96 с жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_d96', 0, 0, '[\"/client/images/products/starline_d96/remote-controls-starline-d96.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_e96-e66', 'remote-controls', 'e96-e66', 'Пульт Starline E96/E66', 'Пульт на автосигнализацию Starline E96/E66 c жидкокристаллическим дисплеем', '27000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_e96-e66', 0, 0, '[\"/client/images/products/starline_e96/starline-E96-V2-BT-ECO-2CAN-4LIN.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_module-2can-2lin', 'remote-controls', 'module-2can-2lin', 'StarLine 2CAN 2LIN Встраиваемый модуль', 'Встраиваемый модуль StarLine GSM+BT предназначен для установки на 5 и 6 поколение автосигнализаций Starline.', '34000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_module-2can-2lin', 0, 0, '[\"/client/images/products/module_starline/module-StarLine-2CAN-2LIN.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_module-bp-03', 'remote-controls', 'module-bp-03', 'Модуль обхода штатного иммобилайзера StarLine BP-03', 'Данный модуль предназначен для обхода штатного иммобилайзера и может работать с любой автосигнализацией с автозапуском. Для работы модуля необходимо поместить в него штатный ключ от автомобиля или чип.', '7000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_module-bp-03', 0, 0, '[\"/client/images/products/module_bp03/module-StarLine-BP-03.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_module-gps', 'remote-controls', 'module-gps', 'StarLine GPS Встраиваемый модуль', 'Внешняя GPS/ГЛОНАСС антенна для автосигнализаций Starline. Устанавливается только совместно c GSM-модулем Starline.', '25000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_module-gps', 0, 0, '[\"/client/images/products/module_starline/module-starline-gps.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_module-gsm3', 'remote-controls', 'module-gsm3', 'StarLine GSM3 Встраиваемый модуль', 'GSM модуль для установки на 3 и 4 поколение автосигнализаций Starline.', '52600.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_module-gsm3', 0, 0, '[\"/client/images/products/module_starline/module-starline-gsm3.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_module-gsm6', 'remote-controls', 'module-gsm6', 'StarLine GSM6+BT Встраиваемый модуль', 'Встраиваемый модуль StarLine GSM+BT предназначен для установки на 5 и 6 поколение автосигнализаций Starline.', '52600.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_module-gsm6', 0, 0, '[\"/client/images/products/module_starline/module-starline-gsm3.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_push-motor', 'remote-controls', 'push-motor', 'Моторчик-толкатель центрального замка', 'Моторчик-толкатель центрального замка для ремонта систем центральных замков', '5000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_push-motor', 0, 0, '[\"/client/images/products/remote-controls/central-lock-motor.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"for-park-systems\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_sd-card', 'remote-controls', 'sd-card', 'Sd-карта памяти для видеорегистраторов', '16GB Micro SD Memory Card UHS-I U1 CLASS 10 SDXC w/ Adapter 100MB/s', '7000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_sd-card', 0, 0, '[\"/client/images/products/sd-card/toshiba-sd-card-16-1.avif\", \"/client/images/products/sd-card/toshiba-sd-card-16-2.avif\", \"/client/images/products/sd-card/toshiba-sd-card-16-3.avif\", \"/client/images/products/sd-card/toshiba-sd-card-16-4.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05'),
('product_remote-controls_sheriff', 'remote-controls', 'sheriff', 'Sheriff Доводчик стекол 4х', 'Sheriff - аналоговый доводчик четырех стекол', '15000.00', '₸', 1, '/product?category=remote-controls&id=product_remote-controls_sheriff', 0, 0, '[\"/client/images/products/remote-controls/sheriff-4x.avif\"]', NULL, NULL, '[\"vnedorojnik\", \"legkoe-avto\"]', '[\"remote-controls\"]', '2025-07-18 12:55:05', '2025-07-18 12:55:05');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `Products`
--
ALTER TABLE `Products`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
